####
#{application}、{profile}等springcloud相关的属性必须配置在bootstrap.properties中，config部分内容才能被正确加载。
#因为config相关的而配置会优先于application.properties，而bootstrap.properties的加载也是优先于application.properties

server: 
    port: 8001

spring: 
    application: 
        name: spring-cloud-config-client                 #对应{application} 部分
